- repo: local

  hooks:
    - id: isort
      name: isort (python)
      entry: isort
      language: system
      types: [python]

    - id: autoflake
      name: autoflake
      entry: autoflake
      language: system
      types: [python]
      args: [--in-place, --remove-all-unused-imports]